version: '3.8'

services:
  prod.backend:
    image: myapp.prod.backend
    container_name: prod.backend
    build:
      context: .
      dockerfile: Dockerfile.prod

    # commented out ports because we are using nginx reverse proxy
    # ports:
    #   - 4000:4000

    env_file:
      - ./.env.production
